Numpy arrays are superfast, and can be considered an extension to python lists, they are very useful in scientific computing and machine learning.

In [1]:
# Numpy Arrays

In [2]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# python lists
python_list = range(1000)
%timeit [i ** 2 for i in python_list]

208 µs ± 611 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
numpy_list = np.arange(1000)
%timeit a**2 # super fast

512 ns ± 3.11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Arrays is numpy can be created in lot of using, but the best way to create numpy arrays is through np.array(), we can create numpy arrays of many dimensions.
Functions such as arange() return an 1D array of that size, linspace() divides the given number of points, ones() creates array of the given size with all '1' in it. Same is with zeros(), '0'. eye() can be used to keep '1's in the diagonal, rest as 0. 

In [6]:
# 1. Creating arrays

In [7]:
# 1-D
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [8]:
# dims
a.ndim

1

In [9]:
# shape
a.shape

(4,)

In [10]:
len(a)

4

In [11]:
# test
aa = np.array([[1, 2, 3, 4]])
print(aa.ndim) 
print(aa.shape)
print((len(aa)))

2
(1, 4)
1


In [12]:
# 2-D, 3-D
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
len(b)

2

In [16]:
# test
bb = np.array([[0, 1, 2], [4, 5]])
print(bb.ndim)
print(bb.shape)
print(len(bb))

1
(2,)
2


In [17]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
c.ndim

3

In [19]:
c.shape

(2, 2, 2)

In [20]:
# Functions for creating arrays

In [21]:
a = np.arange(10) # 0...n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = np.arange(1, 10, 2) # start, end(exclusive), step
b

array([1, 3, 5, 7, 9])

In [23]:
# using linspace
a = np.linspace(0, 1, 6) # start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [24]:
# common arrays
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
c = np.eye(3) # 2-D array with ones on the diagonal and zeros elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
d = np.eye(3, 2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [28]:
# create an array using diaf function
a = np.diag([1, 2, 3, 4]) # construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
np.diag(a) # Extract diagonal

array([1, 2, 3, 4])

In [30]:
# create array using random
# Uniform distribution rand()
a = np.random.rand(4)
a

array([0.39199112, 0.70631065, 0.22235597, 0.83140992])

In [32]:
# Normal distribution randn()
a = np.random.randn(4)
a

array([0.23669909, 0.49235697, 0.48261006, 0.06608744])

In [33]:
# 2. Basic DataTypes

In [34]:
a = np.arange(10)
a.dtype

dtype('int64')

In [36]:
a = np.arange(10, dtype = 'float64') # explicitly specifying the data type
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
# the default data type is float for zeros and ones function
a = np.zeros((3, 3))
print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [38]:
d = np.array([1+2j, 2+4j]) # complex data type
print(d.dtype)

complex128


In [39]:
b = np.array([True, False, True, False]) # Boolean datatype
print(b.dtype)

bool


In [40]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s.dtype

dtype('<U6')

In [41]:
# 3. Indexing and Slicing

In [42]:
# 3.1 Indexing

In [43]:
a = np.arange(10)
print(a[5])

5


In [44]:
a = np.diag([1, 2, 3])
print(a[2, 2])

3


In [45]:
a[2, 1] = 5 # assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [46]:
# Slicing

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a[1:8:2]

array([1, 3, 5, 7])

In [48]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [49]:
b = np.arange(5)
a[5:] = b[::-1] # assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [50]:
# 4. Copies and Views

In [51]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [53]:
np.shares_memory(a, b)

True

In [54]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [55]:
a # even though b was modified, 'a' is updated as well, as they share same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [56]:
a = np.arange(10)

c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [57]:
np.shares_memory(a, c)

False

In [59]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# 5. Fancy Indexing

In [61]:
# Using boolean mask
a = np.random.randint(0, 20, 15)
a

array([ 1, 12,  4,  6,  0, 15,  6, 10,  7,  7,  3, 15,  0,  2,  4])

In [62]:
mask = (a % 2 == 0)

In [63]:
extract_from_a = a[mask]
extract_from_a

array([12,  4,  6,  0,  6, 10,  0,  2,  4])

In [64]:
# Indexing with a mask can be very useful to assign new value to
# a sub array
a[mask] = -1
a

array([ 1, -1, -1, -1, -1, 15, -1, -1,  7,  7,  3, 15, -1, -1, -1])

In [65]:
# Indexing with an array of integers
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [67]:
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])